<a href="https://colab.research.google.com/github/alseo0110/Mosquito-Forecast-System-Analysis/blob/main/data_cleansing1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

csv 파일 읽기

In [ ]:
import pandas as pd

df = pd.read_csv('/content/기온.csv', encoding='EUC-KR')

# df.head()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1621 entries, 0 to 1620
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   		지점번호   1610 non-null   object
 1   지점명      1602 non-null   object
 2   일시       1602 non-null   object
 3   평균기온(℃)  1602 non-null   float64
 4   최고기온(℃)  1602 non-null   float64
 5   	최고기온시각  1602 non-null   object
 6   최저기온(℃)  1601 non-null   float64
 7   최저기온시각   1601 non-null   object
 8   일교차      1601 non-null   float64
dtypes: float64(4), object(5)
memory usage: 114.1+ KB

결측치 찾기

In [ ]:
df[df.isnull().any(axis=1)]

     \t\t지점번호  지점명          일시  평균기온(℃)  최고기온(℃) \t최고기온시각  최저기온(℃) 최저기온시각  일교차
584   \t\t108   서울  2022-08-08     26.8     28.4     0:01      NaN    NaN  NaN
1602      NaN  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1603      NaN  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1604      NaN  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1605      NaN  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1606      NaN  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1607      NaN  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1608      NaN  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1609      NaN  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1610      NaN  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1611      NaN  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1612      NaN  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1613     \t\t  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1614       \t  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1615       \t  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1616       \t  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1617       \t  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1618     \t\t  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1619       \t  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN
1620       \t  NaN         NaN      NaN      NaN      NaN      NaN    NaN  NaN

In [ ]:
df.isna().sum()

\t\t지점번호    11
지점명         19
일시          19
평균기온(℃)     19
최고기온(℃)     19
\t최고기온시각    19
최저기온(℃)     20
최저기온시각      20
일교차         20
dtype: int64

결측치 채우고 필요없는 컬럼 삭제하기

In [ ]:
df.loc[df['일시'] == '2022-08-08', '최저기온(℃)'] = 25.2
df.loc[df['일시'] == '2022-08-08', '일교차'] = 3.2

df = df.dropna()

df = df.drop(columns=['\t\t지점번호', '지점명', '\t최고기온시각', '최저기온시각'])

In [ ]:
df.head()

           일시  평균기온(℃)  최고기온(℃)  최저기온(℃)   일교차
0  2021-01-01     -4.2      1.6     -9.8  11.4
1  2021-01-02     -5.0     -1.4     -8.4   7.0
2  2021-01-03     -5.6     -2.0     -9.1   7.1
3  2021-01-04     -3.5      0.3     -8.4   8.7
4  2021-01-05     -5.5     -2.1     -9.9   7.8

In [ ]:
# 일시 컬럼 datetime 변환
df['일시'] = pd.to_datetime(df['일시'], errors='coerce')

# 연도 필터 (2021~2025)
df = df[df['일시'].dt.year.between(2021, 2025)]

# 월 필터 (5월~10월)
df = df[df['일시'].dt.month.isin([5,6,7,8,9,10])]

저장

In [ ]:
df.to_csv('/content/기온_수정.csv', index = False, encoding="EUC-KR")